defmodule AlaLint.Encoder do
  @moduledoc """
  Best-effort auto-encoding of a codebase into the **ALA Checklist** notation
  (`f` / `[tag]` / edges / `$` / `q`). It produces a *starting draft* a human
  must complete and verify — the tool cannot make the `[tag]` judgement (does
  this code know the product, and at what altitude?), so it fills `[?]` unless a
  layer map is supplied, and it flags — but does not decide — `$` and `q`.

  Output: one `<module-file>.ala.md` per source file, mirrored under an output
  directory, plus an `INDEX.md`.
  """

  alias AlaLint.Layers

  @doc "Return `[{relpath, content}]` — the parallel encoding tree (relpath ends in `.ala.md`)."
  def encode(model) do
    marks = tool_marks(model)

    files =
      model.modules
      |> Enum.group_by(& &1.file)
      |> Enum.map(fn {file, mods} -> {relpath(file, model.root), encode_file(mods, model, marks)} end)
      |> Enum.sort()

    [{"INDEX.md", index(files, model)} | Enum.map(files, fn {rel, body} -> {rel <> ".ala.md", body} end)]
  end

  # The finding-relevant facts the tool can determine and stamp into the encoding,
  # so a completed encoding fed back to `mix ala.lint.encoding` yields the same
  # findings the source lint gives: pass-through ids (`~>`), shared-entity and
  # shared-aggregate modules (`&entity` / `&aggregate`, R10), and the semantic
  # `[?]`/`{app-literal?}`/branch marks the per-function pass already emits.
  defp tool_marks(model) do
    %{
      passthrough: MapSet.new(AlaLint.Rules.passthrough_ids(model), fn {id, _callee} -> id end),
      entity: model |> AlaLint.Rules.r10() |> MapSet.new(& &1.module),
      aggregate: Map.put(model, :check_aggregates, true) |> AlaLint.Rules.r10_aggregate() |> MapSet.new(& &1.module)
    }
  end

  defp relpath(file, root), do: Path.relative_to(file, root)

  defp index(files, model) do
    layered = if model.layers, do: "with a layer map (levels `@name-Lidx` assigned; semantic `[?]` tags for a human)", else: "WITHOUT a layer map (no levels; `[?]` tags for a human)"
    rows = Enum.map_join(files, "\n", fn {rel, _} -> "- `#{rel}.ala.md`" end)

    """
    # ALA encoding — #{length(files)} files (#{model.function_total} functions)

    Auto-generated by `ala_lint` #{layered}. **This is a draft; a human must complete it.**
    See the checklist at the top of each file. Checklist: `ala-checklist.md`.

    #{rows}
    """
  end

  defp encode_file(mods, model, marks) do
    header() <> Enum.map_join(mods, "\n", &encode_module(&1, model, marks))
  end

  defp header do
    """
    # AUTO-ENCODED (ALA Checklist) — INCOMPLETE. A human must:
    #   • assign each [?] semantic tag: does this code know the product, and what does it know? (the tool can't judge this)
    #   • the @name-Lidx level is the tool's layer assignment; verify it, and check it agrees with your [tag]
    #   • confirm every edge DROPS to a more-abstract callee; a same-tag edge may be cohesion or peer coupling
    #   • confirm $ (hidden state) is a real hidden channel, not legitimate instance state
    #   • confirm each q (shared literal) is a genuine silent contract to single-source
    #   • resolve each {app-literal?}: rewrite to {app-literal} (an application literal — belongs at the top, hoist if it isn't) or
    #       {intrinsic-literal} (intrinsic to the abstraction, kept local). Value is opaque; `mix ala.lint` has the file:line
    #   • add p/*p (data wires) and (p)-> (composition lambdas) by reading the code — the tool can't infer these
    # Tool-stamped marks (already decided; keep them for a faithful re-lint):
    #   &entity  = module shares a domain entity/struct with peers (R10);  &aggregate = shared across too many peers (R10 aggregate)
    #   ~>       = pass-through: public fn with one caller and one cross-module callee, renaming without hiding a decision (R7-adjacent)
    #   (branches) = an application-layer function that itself branches (R11: the top should compose, not decide)
    # ─────────────────────────────────────────────────────────────────────────

    """
  end

  defp encode_module(m, model, marks) do
    # Two slots: `[?]` is the SEMANTIC tag (what does this know? — a human fills
    # it), `@name-Lidx` is the LAYER/level (which tier? — the tool assigns it
    # from the map). The level lives once on the module line; a function repeats
    # it only to OVERRIDE (when its own `@ala_layer` differs from the module's).
    # Fully-qualified `Module.fun/arity` keeps every line globally-unique and
    # grep-able. `{app-literal?}` seeds an application-literal candidate (value opaque; run
    # `mix ala.lint` for its file:line) to resolve to `{app-literal}`/`{intrinsic-literal}`.
    mlayer = layer_of(m.name, model)
    cfg = cfg_functions(m)

    funs =
      m.functions
      |> Enum.map(fn f ->
        mark = if MapSet.member?(cfg, {f.name, f.arity, f.line}), do: "   {app-literal?}", else: ""
        flayer = fun_layer_of({m.name, f.name, f.arity}, model)
        override = if flayer != nil and flayer != mlayer, do: level_suffix(flayer), else: ""
        pt = if MapSet.member?(marks.passthrough, {m.name, f.name, f.arity}), do: "  ~>", else: ""
        br = if app_branchy?(f, m, model), do: "  (branches)", else: ""
        "  f #{m.name}.#{f.name}/#{f.arity}#{if f.private, do: " (private)", else: ""}   [?]#{mark}#{override}#{pt}#{br}"
      end)
      |> Enum.join("\n")

    edges = encode_edges(m, model, mlayer)
    state = encode_state(m)
    contracts = encode_contracts(m, model)

    """
    module #{m.name}   [?]#{level_suffix(mlayer)}#{entity_mark(m, marks)}
    #{funs}
    #{edges}#{state}#{contracts}
    """
  end

  defp entity_mark(m, marks) do
    cond do
      MapSet.member?(marks.aggregate, m.name) -> "   &aggregate"
      MapSet.member?(marks.entity, m.name) -> "   &entity"
      true -> ""
    end
  end

  # An application-layer function that itself branches: the top tier should
  # compose, not decide (R11). Non-app functions branch freely.
  defp app_branchy?(f, m, %{layers: %{app_layers: app}} = model) do
    case fun_layer_of({m.name, f.name, f.arity}, model) do
      {_name, idx} -> MapSet.member?(app, idx) and AlaLint.Rules.branchy?(f.body)
      _ -> false
    end
  end

  defp app_branchy?(_f, _m, _model), do: false

  defp encode_edges(m, model, mlayer) do
    deps =
      m.refs
      |> Enum.filter(&MapSet.member?(model.module_names, &1))
      |> Enum.reject(&(&1 == m.name))
      |> Enum.sort()

    case deps do
      [] -> "  (no project edges)\n"
      _ ->
        lines =
          Enum.map_join(deps, "\n", fn dep ->
            dl = layer_of(dep, model)
            "    → #{dep} #{level_token(dl)}   #{edge_note(mlayer, dl, m.name, dep, model)}"
          end)

        "  depends on:\n" <> lines <> "\n"
    end
  end

  # Judge the edge from the two endpoints' layer indices; prompt the human when
  # either side is unassigned.
  defp edge_note(nil, _dl, _a, _b, _model), do: "(verify: does this drop?)"
  defp edge_note(_ml, nil, _a, _b, _model), do: "(verify: does this drop?)"

  defp edge_note({_, ia}, {_, ib}, a, b, %{layers: %{peer_ok: peer_ok, units: units}}) do
    cond do
      ib > ia -> "drops ✓"
      ib < ia -> "⚠ UP — knowledge flows up (R1)"
      Map.get(peer_ok, ia, true) -> "same layer (composition/internal ok)"
      Layers.unit(a, units[ia]) == Layers.unit(b, units[ia]) -> "same unit (cohesion ok)"
      true -> "⚠ PEER — feature↔feature coupling (R1)"
    end
  end

  defp edge_note(_ml, _dl, _a, _b, _model), do: "(verify: does this drop?)"

  # A function's/module's layer as `{name, index}` (index 0 = top), or nil.
  defp layer_of(_name, %{layers: nil}), do: nil
  defp layer_of(name, %{layers: %{index: idx, names: names}}), do: at_layer(Map.get(idx, name), names)

  defp fun_layer_of(_id, %{layers: nil}), do: nil
  defp fun_layer_of(id, %{layers: %{fun_index: fi, names: names}}), do: at_layer(Map.get(fi, id), names)

  defp at_layer(nil, _names), do: nil
  defp at_layer(i, names), do: {to_string(Enum.at(names, i)), i}

  defp level_suffix(nil), do: ""
  defp level_suffix({name, idx}), do: "  @#{name}-L#{idx}"

  defp level_token(nil), do: "[?]"
  defp level_token({name, idx}), do: "@#{name}-L#{idx}"

  defp encode_state(m) do
    kinds = m.state_ops |> Enum.map(fn {{k, _}, _} -> k end) |> Enum.uniq()
    if kinds == [], do: "", else: "  $ #{Enum.join(kinds, ", ")}   -- VERIFY: hidden channel, or legit instance state? (R4)\n"
  end

  # Functions that own at least one configuration-candidate literal, by the same
  # `magic?` test the source R3 scan uses. A literal at line L belongs to the
  # function with the greatest def-line ≤ L (the R3 attribution rule).
  defp cfg_functions(m) do
    for {lit, line} <- m.literals, AlaLint.Rules.magic?(lit), f = owner_fun(m.functions, line), f != nil, into: MapSet.new() do
      {f.name, f.arity, f.line}
    end
  end

  defp owner_fun(functions, line) do
    functions |> Enum.filter(&(&1.line <= line)) |> Enum.max_by(& &1.line, fn -> nil end)
  end

  defp encode_contracts(m, model) do
    shared =
      for {{:string, s}, mods} <- model.literal_index,
          MapSet.member?(mods, m.name),
          MapSet.size(mods) >= 2,
          String.length(s) in 3..40,
          not String.match?(s, ~r/\s/) do
        s
      end
      |> Enum.uniq()
      |> Enum.take(6)

    if shared == [], do: "", else: "  q #{Enum.map_join(shared, ", ", &inspect/1)}   -- VERIFY: silent contract to single-source? (R5)\n"
  end

end
